# src/configs/base_config.yaml
# Contient tous les paramètres partagés par nos expériences

seed: 42

experiment:
  # Les chemins sur le cluster
  output_dir: "/sps/liris/eebou/htr_outputs"
  log_dir: "/sps/liris/eebou/htr_logs"
  # Le nom sera surchargé par chaque expérience

model:
  global_dim: 512

data:
  data_list_file: "/sps/liris/eebou/datasets/htr_valid_paths.txt"
  target_height: 128
  batch_size: 256
  num_workers: 8

loss:
  global_temp: 0.2
  lambda_global: 1.0
  queue_size: 16384 # Plus de négatifs, car on a plus de VRAM

training:
  num_epochs: 50
  momentum: 0.996
  warmup_epochs: 5
  validate_every_n_epochs: 1
  save_every_n_epochs: 5
  early_stopping:
    enabled: true
    patience: 10
    monitor: "val_contrastive_acc"
    mode: "max"

optimizer:
  type: "adamw"
  betas: [0.9, 0.999]

scheduler:
  type: "cosine"
  min_lr: 1e-6

advanced:
  use_amp: true
  compile_model: true
  channels_last_memory_format: true