# Expérience C : Hypothèse "Apprentissage Doux"
seed: 42
experiment:
  name: "exp_C_slower_lr"
  output_dir: "/sps/liris/eebou/htr_outputs"
  log_dir: "/sps/liris/eebou/htr_logs"
model:
  global_dim: 512
data:
  data_list_file: "/sps/liris/eebou/datasets/htr_valid_paths.txt"
  target_height: 128
  batch_size: 256
  num_workers: 16
augmentation:
  strength: 0.7
loss:
  global_temp: 0.2
  queue_size: 16384
training:
  num_epochs: 50
  learning_rate: 1e-4 # Plus faible
  weight_decay: 5e-4
  momentum: 0.996
  warmup_epochs: 10 # Plus long
  validate_every_n_epochs: 1
  early_stopping: { enabled: true, patience: 10, monitor: "val_contrastive_acc", mode: "max" }
optimizer: { type: "adamw" }
scheduler: { type: "cosine", min_lr: 1e-6 }
advanced: { use_amp: true, compile_model: true }